
OCAMLC ?= $(OCAMLFIND) ocamlc
OCAMLOPT ?= $(OCAMLFIND) ocamlopt

MLPPOPT = 
MLFLAGS = -package camlp4,camlp4.macro -syntax camlp4r -w +7+9 -g

%.cmi: %.mli
	$(OCAMLC) $(MLFLAGS) -c $<

%.cmo: %.ml
	$(OCAMLC) $(MLFLAGS) $(if $(MLPPOPT),$(patsubst %,-ppopt %,$(MLPPOPT))) -c $<

%.cmx: %.ml
	$(OCAMLOPT) $(MLFLAGS) -S $(if $(MLPPOPT),$(patsubst %,-ppopt %,$(MLPPOPT))) -c $<

%.o: %.c
	$(OCAMLOPT) -I . -verbose -g  $(if $(CFLAGS),$(patsubst %,-ccopt %,$(CFLAGS)))  -ccopt '-o $@' -c $<

%.o: %.m
	  $(OCAMLOPT) -I . -verbose -g  $(if $(CFLAGS),$(patsubst %,-ccopt %,$(CFLAGS))) -ccopt '-fPIC' -ccopt '-o $@' -c $<
