OCAMLFIND = ocamlfind -toolchain ios
OCAMLOPT = $(OCAMLFIND) ocamlopt
OCAMLC = $(OCAMLFIND) ocamlc
OCAMLLIBDIR = $(shell ${OCAMLOPT} -where)
include Makefile.common

MOBS = ios/AppDelegate.o ios/main.o
CFLAGS += -I ../src/ios


include Makefile.in

res:
	aresmkr -concat -i Resources -o ios/LightTest/assets
	aresmkr -merge -o ios/LightTest/index ios/LightTest/assets
	rm ios/LightTest/assets.index

ios: $(TARGET).native
	cp test.native ios/LightTestBin

.DEFAULT_GOAL := ios

clean::
	rm -f LightTest/*.o
