OCAMLFIND = ocamlfind -toolchain android
OCAMLOPT = $(OCAMLFIND) ocamlopt
OCAMLC = $(OCAMLFIND) ocamlc
include Makefile.common
include Makefile.in

-include target

TARGET ?= example

res:	
	#aresmkr -concat -i Resources -o android/assets/assets
	#aresmkr -merge -o android/assets/index android/assets/assets
	rm android/assets/assets.index

so: $(TARGET).so res
	cp test.so android/libs/armeabi-v7a/libtest.so
	ant -f android/build.xml debug

release: $(TARGET).so
	cp test.so android/libs/armeabi-v7a/libtest.so
	ant -f android/build.xml release

$(TARGET).so: $(MLXFILES) $(TARGET).cmx
	$(OCAMLOPT) -verbose -o test.so  -g  \
	-I ../src ../src/lightning.cmxa  $(OAUTHX) $(SOCIALX) $(MOBS) $(MLXFILES) ../src/social/facebook/fb.cmxa $(TARGET).cmx \
	-package extlib,xmlm,ojson,bigarray,redspell.debug -linkpkg -cclib "-L../src/android/libpng" -cclib "-L../src/android/libjpeg" -cclib "-L../src/android/libcurl" -cclib "-L../src/social/facebook" -output-obj

clean::
	rm -f LightTest/*.o LighTest/*.so 


.DEFAULT_GOAL = so
