OCAMLFIND = ocamlfind -toolchain android
OCAMLOPT = $(OCAMLFIND) ocamlopt
OCAMLC = $(OCAMLFIND) ocamlc
include Makefile.common
include Makefile.in

-include target

TARGET ?= example

res:	
	aresmkr -concat -i Resources -o android/assets/assets
	#aresmkr -concat -i Resources -o android-expansion 
	aresmkr -merge -o android/assets/index android/assets/assets
	rm android/assets/assets.index

so: $(TARGET).so res
	cp test.so android/libs/armeabi-v7a/libtest.so
	ant -f android/build.xml debug

release: $(TARGET).so
	cp test.so android/libs/armeabi-v7a/libtest.so
	ant -f android/build.xml release



$(TARGET).so: $(CFILES) $(MLXFILES) $(TARGET).cmx
	$(OCAMLOPT) -verbose -o test.so  -g  \
	-I ../src ../src/lightning.cmxa \
	-cclib "-L../src/plugins/facebook" ../src/plugins/facebook/facebook.cmxa \
	-cclib "-L../src/plugins/mobileapptracking"  ../src/plugins/mobileapptracking/mobileapptracking.cmxa \
	-cclib "-L../src/plugins/tapjoy" ../src/plugins/tapjoy/tapjoy.cmxa \
	-cclib "-L../src/plugins/chartboost" ../src/plugins/chartboost/chartboost.cmxa \
	-cclib "-L../src/plugins/flurry" ../src/plugins/flurry/flurry.cmxa \
	-cclib "-L../src/plugins/sponsorpay" ../src/plugins/sponsorpay/sponsorpay.cmxa \
	-cclib "-L../src/plugins/appflood" ../src/plugins/appflood/appflood.cmxa \
	-cclib "-L../src/plugins/supersonic" ../src/plugins/supersonic/supersonic.cmxa \
	-cclib "-L../src/plugins/twitter" ../src/plugins/twitter/twitter.cmxa \
	-cclib "-L../src/plugins/instagram" ../src/plugins/instagram/instagram.cmxa \
	-cclib "-L../src/plugins/whatsapp" ../src/plugins/whatsapp/whatsapp.cmxa \
	-cclib "-L../src/plugins/appsflyer" ../src/plugins/appsflyer/appsflyer.cmxa \
	$(OAUTHX) $(SOCIALX) $(MLXFILES) $(CFILES) $(TARGET).cmx \
	-package extlib,xmlm,ojson,bigarray,redspell.debug -linkpkg -cclib "-L../src/android/libpng" -cclib "-L../src/android/libjpeg" -cclib "-L../src/android/libcurl" \
	-output-obj

clean::
	rm -f LightTest/*.o LighTest/*.so 


.DEFAULT_GOAL = so
