
MLPPOPT = 
MLFLAGS = -package camlp4,camlp4.macro -syntax camlp4r 
MLCOMPFLAGS = -w +7+9 -warn-error +10 -g

%.cmi: %.mli
	$(OCAMLC) $(MLFLAGS) $(MLCOMPFLAGS) -c $<

%.cmo: %.ml
	$(OCAMLC) $(MLFLAGS) $(MLCOMPFLAGS) $(if $(MLPPOPT),$(patsubst %,-ppopt %,$(MLPPOPT))) -c $<

%.cmx: %.ml
	$(OCAMLOPT) $(MLFLAGS) $(MLCOMPFLAGS) $(if $(MLPPOPT),$(patsubst %,-ppopt %,$(MLPPOPT))) -c $<
