#!/bin/bash

echo "cleaning..."

rm `find . -name "*.o"`

echo "done, compiling..."

r () 
{ 
    for d in "$1"/*
    do
        if [[ $d != "." && $d != ".." ]]; then
            if [ -d "$d" ]; then
                ( r "$d" )
            else
                if [[ $d == *.m ]]; then
                    cmd="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -miphoneos-version-min=5.1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk -I. -I./Categories -I./Reachability -I./URLGeneration -I./URLGeneration/ParameterProviders -I./Utils -I./VCS -I./VCS/SBJson -I./iToast -c $d"
                    echo $cmd
                    $cmd
                fi
            fi;            
        fi;
    done
}

r "."

echo "done, making library archive..."

find . -name "*.o" -not -name "OpenUDID.o" -print0 | xargs -0 -J % ar -r ../libsponsorpay-sdk.a %

echo "done, copying headers..."

rm -rf ../include/
mkdir -p ../include
find . -name "*.h" -not -path "*ParameterProviders*" -print0 | xargs -0 -J % cp % ../include
mkdir -p ../include/ParameterProviders
find . -path "*ParameterProviders*.h" -print0 | xargs -0 -J % cp % ../include/ParameterProviders

echo "done"