
include config.ios
include Makefile.common

MOBS = Code/AppDelegate.o iPad/AppDelegate_iPad.o Shared/main.o  
LIGHTNING_PATH=lightning_ios/src
CFLAGS += -I $(LIGHTNING_PATH)/ios
LINKFLAGS = -ccopt -LCode/Hamsters/chipmunk/ml -ccopt -LCode/Hamsters/chipmunk/src Code/Hamsters/chipmunk/ml/chipmunk.cmxa 
MLPPOPTS += -enable-debug default

include Makefile.in
