#!/bin/bash

echo "compiling..."

r () 
{ 
    for d in "$1"/*
    do
        if [[ $d != "." && $d != ".." ]]; then
            if [ -d "$d" ]; then
                ( r "$d" )
            else
                if [[ $d == *.m ]]; then
                    cmd="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -miphoneos-version-min=5.1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk -I./sdk -I./sdk/Categories -I./sdk/Reachability -I./sdk/URLGeneration -I./sdk/URLGeneration/ParameterProviders -I./sdk/Utils -I./sdk/VCS -I./sdk/VCS/SBJson -I./sdk/iToast -c $d"
                    echo $cmd
                    $cmd
                fi
            fi;            
        fi;
    done
}

r "sdk"

echo "done, making library archive..."

find . -name "*.o" -not -name "OpenUDID.o" -print0 | xargs -0 -J % ar -r libsponsorpay-sdk.a %
find . -name "*.o" -delete

echo "done, copying headers..."

rm -rf include
mkdir -p include
find . -name "*.h" -not -path "*ParameterProviders*" -print0 | xargs -0 -J % cp % include
mkdir -p include/ParameterProviders
find . -path "*ParameterProviders*.h" -print0 | xargs -0 -J % cp % include/ParameterProviders

echo "done"