# Makefile.config written by configure
OCAML_CORE_STDLIB=/usr/local/ocaml/4.01.0/lib
OCAML_CORE_BIN=/usr/local/ocaml/4.01.0/bin
OCAML_CORE_MAN=/usr/local/ocaml/4.01.0/man
OCAML_SITELIB=/usr/local/ocaml/4.01.0/lib/site-lib
OCAML_THREADS=posix
OCAMLFIND_BIN=/usr/local/ocaml/4.01.0/bin
OCAMLFIND_MAN=/usr/local/ocaml/4.01.0/man
OCAMLFIND_CONF=/usr/local/ocaml/4.01.0/etc/findlib.conf
OCAML_AUTOLINK=true
OCAML_REMOVE_DIRECTORY=1
EXEC_SUFFIX=
CUSTOM=-custom
PARTS=findlib
INSTALL_TOPFIND=1
USE_CYGPATH=0
VERSION=1.4
SYSTEM=macosx
