# Makefile.config written by configure
OCAML_CORE_STDLIB=/usr/local/lib/ocaml
OCAML_CORE_BIN=/opt/local/bin
OCAML_CORE_MAN=/opt/local/man
OCAML_SITELIB=/usr/local/lib/ocaml/site-lib
OCAML_THREADS=posix
OCAMLFIND_BIN=/opt/local/bin
OCAMLFIND_MAN=/opt/local/man
OCAMLFIND_CONF=/opt/local/etc/findlib.conf
OCAML_AUTOLINK=true
EXEC_SUFFIX=
PARTS=findlib
INSTALL_TOPFIND=1
USE_CYGPATH=0
VERSION=1.2.7
SYSTEM=macosx
